# Common settings.
domain: knative.example.com
MSE_EUREKA_URL: mse-xxx-eureka.mse.aliyuncs.com

ingress:
  host: hl-dev.knative.example.com
  mobile:
    headers:
      User-Agent:
        regex: .*Mobile.*

portalpc:
  name: portal-pc
  image:
    repository: "registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-portal-pc"
    tag: "master_71550dd3-20191118170322"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10

portalmobile:
  name: portal-mobile
  image:
    repository: "registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-portal-mobile"
    tag: "master_71550dd3-20191118170150"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10

baseinfo:
  image:
    repository: "registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-baseinfo"
    tag: "master_71550dd3-20191118170440"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10
  port: "80"

contactinfo:
  image:
    repository: "registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-contactinfo"
    tag: "master_71550dd3-20191118170545"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10
  port: "80"

