# Common settings.
namespace: default
domain: example.com
MSE_EUREKA_URL: mse-xxxx-eureka.mse.aliyuncs.com

ingress:
  host: test.example.com
  mobile:
    headers:
      User-Agent:
        regex: .*Mobile.*


portalwww:
  name: portal-www
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-portal-www
    tag: "master_71550dd3-20191117222711"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10

portalmobile:
  name: portal-mobile
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-portal-wap
    tag: "master_71550dd3-20191117224805"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10

baseinfo:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-baseinfo
    tag: "master_71550dd3-20191117221027"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10
  port: "80"

contactinfo:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/knative-sample/cms-contactinfo
    tag: "master_71550dd3-20191117222557"
  maxScale: "100"
  minScale: "1"
  containerConcurrency: 10
  port: "80"