server:
  port: 8081
spring:
  application:
    name: contactinfo
eureka:
  client:
    serviceUrl:
      defaultZone: http://${MSE_EUREKA_URL}:8761/eureka
      #defaultZone: http://mse-1cc947c3-p.eureka.mse.aliyuncs.com:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: ${ENDPOINT_HOST}
    nonSecurePort: ${ENDPOINT_PORT}

