apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.portalwww.name }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "{{ .Values.portalwww.maxScale }}"
        autoscaling.knative.dev/minScale: "{{ .Values.portalwww.minScale }}"
    spec:
      containerConcurrency: {{ .Values.portalwww.containerConcurrency }}
      containers:
      - image: "{{ .Values.portalwww.image.repository }}:{{ .Values.portalwww.image.tag }}"
        env:
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.portalmobile.name }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "{{ .Values.portalmobile.maxScale }}"
        autoscaling.knative.dev/minScale: "{{ .Values.portalmobile.minScale }}"
    spec:
      containerConcurrency: {{ .Values.portalmobile.containerConcurrency }}
      containers:
      - env:
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.portalmobile.image.repository }}:{{ .Values.portalmobile.image.tag }}"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: baseinfo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "{{ .Values.baseinfo.maxScale }}"
        autoscaling.knative.dev/minScale: "{{ .Values.baseinfo.minScale }}"
    spec:
      containerConcurrency: {{ .Values.baseinfo.containerConcurrency }}
      containers:
      - env:
        - name: ENDPOINT_HOST
          value: baseinfo.{{ .Release.Namespace }}.{{ .Values.domain }}
        - name: ENDPOINT_PORT
          value: "{{ .Values.baseinfo.port }}"
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.baseinfo.image.repository }}:{{ .Values.baseinfo.image.tag }}"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contactinfo
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "{{ .Values.contactinfo.maxScale }}"
        autoscaling.knative.dev/minScale: "{{ .Values.contactinfo.minScale }}"

    spec:
      containerConcurrency: {{ .Values.contactinfo.containerConcurrency }}
      containers:
      - env:
        - name: ENDPOINT_HOST
          value: contactinfo.{{ .Release.Namespace }}.{{ .Values.domain }}
        - name: ENDPOINT_PORT
          value: "{{ .Values.contactinfo.port }}"
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.contactinfo.image.repository }}:{{ .Values.contactinfo.image.tag }}"
