apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.portalwww.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        {{- if not .Values.contactinfo.scaleToZero }}
        autoscaling.knative.dev/minScale: "1"
        {{- end }}
    spec:
      containerConcurrency: 10
      containers:
      - image: "{{ .Values.portalwww.image.repository }}:{{ .Values.portalwww.image.tag }}"
        env:
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}

---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.portalmobile.name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        {{- if not .Values.contactinfo.scaleToZero }}
        autoscaling.knative.dev/minScale: "1"
        {{- end }}
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.portalmobile.image.repository }}:{{ .Values.portalmobile.image.tag }}"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: baseinfo
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        {{- if not .Values.contactinfo.scaleToZero }}
        autoscaling.knative.dev/minScale: "1"
        {{- end }}
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: ENDPOINT_HOST
          value: baseinfo.{{ .Values.namespace }}.{{ .Values.domain }}
        - name: ENDPOINT_PORT
          value: "80"
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.baseinfo.image.repository }}:{{ .Values.baseinfo.image.tag }}"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contactinfo
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "100"
        {{- if not .Values.contactinfo.scaleToZero }}
        autoscaling.knative.dev/minScale: "1"
        {{- end }}

    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: ENDPOINT_HOST
          value: contactinfo.{{ .Values.namespace }}.{{ .Values.domain }}
        - name: ENDPOINT_PORT
          value: "80"
        - name: MSE_EUREKA_URL
          value: {{ .Values.MSE_EUREKA_URL }}
        image: "{{ .Values.contactinfo.image.repository }}:{{ .Values.contactinfo.image.tag }}"
